language: minimal

branches:
  except:
    - master

deploy:
  provider: script
  skip_cleanup: true

  script:
  - ./.travis/deploy.py

  on:
    branch: development

env:
  global:
    # GH_TOKEN
    secure: X24ljRczTwz0m2KkefTgkuEHf3ZKNaWEthgW1VK/ddA3j3qpStjRjQ1JnAILBIbljNUbvCU7Q8x6/EGnOeGpuFfsEp+4Rzjj26+0OOFcTx8RliNQ23tskqVbsBSZYMqbqt9ZYkj7HBdl1SDrnGy78ZxSwG7jKSiu6Wn9fHTLaJTEdo+Ilqsdf8nCtX0TuYMWr/9698AtCez9bxUCXv6b/pkUtive3jpxi9pymq3GABDtcdXY5wJZIY9suvm5r6DvDbapNigIvxZd5j9wtn+m6uBNWrE2s1w4etUsqHHM+DyEnS41hMQ2WkXk5tjlxzoeomEMkdMiqxFRmfIvPUW3UQKbts5Zm270tkyGHShl1XDG13pltxHnKziLurhsNjObiA5gI8j+Dn/jb+8bLdisOH4jvCEY1pvhKdHLyvZC0y/3ZFTVSGTkBT1YHmsYSfgCFLsJUWXyUTwVNZtOK0N67Yquk4/QF/h/CA7Ix8SMsWwP1KOB350z2zwRaYh1PtEfL3uBnaQicsm2RQCMd4ESSyiH0NbiS1DWAXCtsksqCn5bWkrWRZbcxS2LYaqZRWkXbz6V0W6E73VXa+8BJDWE9aU4eL45eZxh/9uKRSY9sxvMbbIvxBpUUfYSgyThao9IEGxzV83upbmyT7AFa/lxVoiwyDbbX32sB8T3VAcACJU=
