title = "~ruben"
base_url = "https://www.rubys.ninja"
compile_sass = true
minify_html = true

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "base16-ocean-dark", filename = "syntax-theme-dark.css" },
  { theme = "base16-ocean-light", filename = "syntax-theme-light.css" },
]
extra_syntaxes_and_themes = ["syntaxes"]

[extra]
menu = [
    { name = "~ruben", url = "/" },
    { name = "/blog", url = "/blog" },
    { name = "/TIL", url = "/til" },
    { name = "/projects", url = "/projects" },
    { name = "/reading", url = "/reading-list" },
]

rss_feeds = [
  { name = "Blog", url = "/blog/atom.xml" },
  { name = "TIL", url = "/til/atom.xml" },
]

mathjax = true
mathjax_dollar_inline_enable = true
