title = "Tau's Website"
base_url = "https://tau.garden"
compile_sass = true
minify_html = true

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "catppuccin-frappe", filename = "syntax-theme-dark.css" },
  { theme = "catppuccin-latte", filename = "syntax-theme-light.css" },
]
extra_syntaxes_and_themes = ["syntaxes"]

[extra]
menu = [
    { name = "Home", url = "/" },
    { name = "Blog", url = "/blog" },
    { name = "TIL", url = "/til" },
    { name = "Reading", url = "/reading-list" },
]

feeds = ['blog/_index.md', 'til/_index.md']
