name: CI

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Build
      run: ./scripts/build.sh

    - name: Upload GitHub Pages Artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./build

  deploy_pages:
    needs: build
    if: success() && github.ref_name == 'main'

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
