name: CI

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Build
      run: ./scripts/build.sh

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.4.0
      if: success() && github.ref == 'refs/heads/development' && github.repository == 'bash/bash.github.io'
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./build
