name: CI

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.x'

    - name: Install dependencies
      run: gem install dpl --version 2.0.0.alpha.5

    - name: Deploy
      run: dpl pages git --target_branch master --local_dir build --committer_from_gh
      if: github.ref == 'refs/heads/development' && github.repository == 'bash/bash.github.io'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
